{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "azure-ai-saas.name" . }}-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azure-ai-saas.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: eg
    namespace: envoy-gateway-system
  hostnames:
  - azure-web.dev.local
  rules:
  - matches:
    - path:
        type: {{ .Values.httpRoute.pathType }}
        value: {{ .Values.httpRoute.path }}
    backendRefs:
    - name: {{ include "azure-ai-saas.name" . }}-service
      port: {{ .Values.service.port }}
{{- end }}

